### ISSUE TITLE
你好 能提供下数据库文件吗

### ISSUE THREAD

**Issue by Qiufcong** [sinoaube/course-scheduling-system#1]

**Comment by Qiufcong** [comment]
如果可以的话 请发邮箱79901198@qq.com

**Comment by Qiufcong** [comment]
谢谢

**Comment by sylviax26** [comment]
你好，项目使用了ORM，在启动时，会根据models中的结构自动创建数据库中的各表。
你只需要在conf/app.conf中配置好数据库连接信息。

**Comment by sylviax26** [comment]
如果需要测试数据，你可以使用附带工具导入测试数据。
在项目根目录下运行 `go run ./dev/importDummyData`，它会导入/dev/data下的excel表到数据库中。
